### ISSUE TITLE
[Feature] Place non-code digital assets in their own repo

### ISSUE THREAD

**Issue by shahankhatch** [bitdao-io/bitdao-governance#48]
## Feature Description

Currently, non-code assets (e.g., SVG files, logos, fonts) are sprinkled across projects. E.g., the landing page includes the digital assets, while the delegate page references an S3 bucket (managed by a different team).

In order to establish improved control over our digital assets, place all non-code digital assets in their own repo and version the repo. 

This will allow more stable development, testing, and deployment as we produce releases. Products that rely on these assets can then be upgraded at their corresponding pace.

In addition to this repo, this issue also affects the landing page repo.
https://github.com/bitdao-io/bitdao-interface

**Comment by octavioamu** [comment]
I was thinking on this and I believe will add a lot of friction for development, using tools like https://www.npmjs.com/package/s3-folder-upload to sync the new assets to s3 on deploy time seems a better approach, even we can have setup on env's for staging and production.

**Comment by octavioamu** [comment]
Closing as solved on #76
